spring.application.name=game-library
# Server Port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:gamedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console (Accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Steam API Configuration
steam.api.key=${STEAM_API_KEY:CC807C8BCC609091419147A665D66FE5}
steam.api.base-url=https://api.steampowered.com